export {
  OSC_TYPES,
  FILTER_TYPES,
  LFO_WAVEFORMS,
  LFO_TARGETS,
  KNOWN_LLM_PATCH_VERSIONS,
  assertKnownLlmPatchVersion,
  decodeLlmPatch,
  convertLlmPatch,
  validatePatch,
} from './lib/patchCodec';
export type {
  OscTypeName,
  FilterTypeName,
  LfoWaveformName,
  LfoTargetName,
  LlmOsc,
  LlmFilter,
  LlmEnv,
  LlmLfo,
  LlmReverb,
  LlmDelay,
  LlmPatch,
  KnownLlmPatchVersion,
  CodecErrorCode,
  CodecError,
  DecodeLlmPatchResult,
} from './lib/patchCodec';
