// ── Prompt sync: C++ .md sources → generated TS constants (#280) ────
//
// Reads src/mapper/enhancer-prompt.md and src/mapper/system-prompt.md
// (paths resolved relative to this script via import.meta.url) and
// emits netlify/functions/lib/prompts.generated.mts. The generated file
// is gitignored — run this in CI BEFORE the functions bundle is built:
//
//     node scripts/sync-prompts.mjs
//
// The .md files stay the single source of truth; never hand-edit the
// emitted file.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const outFile = join(root, "netlify", "functions", "lib", "prompts.generated.mts");

const enhancer = readFileSync(join(root, "src", "mapper", "enhancer-prompt.md"), "utf8");
const system = readFileSync(join(root, "src", "mapper", "system-prompt.md"), "utf8");

// The emitted constant is a String.raw template literal: backslashes in
// the .md stay literal. Backticks and ${ sequences cannot appear raw in
// a template, so both are spliced as template expressions — defensively
// in that order, so a literal "${" in the source survives verbatim.
function emit(name, text) {
  const guarded = text
    .replace(/\$\{/g, "${\"$\"}{")
    .replace(/`/g, "${\"`\"}");
  return `export const ${name} = String.raw\`${guarded}\`;\n`;
}

const header =
  "// GENERATED by scripts/sync-prompts.mjs — do not edit.\n" +
  "// Source of truth: src/mapper/enhancer-prompt.md and src/mapper/system-prompt.md.\n\n";

const out =
  header +
  emit("ENHANCER_PROMPT", enhancer) +
  "\n" +
  emit("SYSTEM_PROMPT", system);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`wrote ${outFile} (enhancer ${enhancer.length} chars, system ${system.length} chars)`);
